version: "3"
services:
  web:
    image: iamkryfor/tpp_status_api:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.05"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9030:9030"
    networks:
      - webnet
networks:
  webnet: